name: spec

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Build and test with Rake
      run: |
        cp template.yaml.sample template.yaml
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake pt-fingerprint:download
        bundle exec rake
